### PR TITLE
OpenRCT2 no longer crashes after station abuse.

### LINKED ISSUE #1157: Crashing on opening Starpointe
Source: https://openrct.net/forum/topic/42/starpointe-crashing-openrct

Hi, 

Im still pretty new to all this! So I just want to say, I LOVE OpenRCT!!!! It's really gotten me back into the game. 
I am having a problem when trying to load the park, Starpointe. 
I am receiving the following errors:

http://i.imgur.com/UCwKlaz.png
http://i.imgur.com/vEX4oyR.png

Im guessing this crash is from the Amazing Earl rides and whatever else is showing the CMD box?
If you haven't played Starpoint - I believe it may be one of the BEST RCT2 parks around. You can download the park from NE Designs here: http://www.nedesigns.com/park/2914/starpointe/
Thanks!
- Taylor

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Certain 8cars functions would move station track pieces that would cause the game to crash as they would not be at the correct location. OpenRCT2 will just skip trying to update the tiles of station track that has been modified this way

Fixes #1157 and any other custom map with station abuse.

### CODE REVIEW

File: src/ride/station.c [hunk 1]
```diff
@@ -291,6 +291,10 @@ static void ride_invalidate_station_start(rct_ride *ride, int stationIndex, int
 	y = (ride->station_starts[stationIndex] >> 8) * 32;
 	mapElement = ride_get_station_start_track_element(ride, stationIndex);
 
+	// If no station track found return
```
Comment (IntelOrca) [inline src/ride/station.c]: Commenting the obvious :p ... Probably better to say FIX for rare occasions.

Comment (duncanspumpkin) [inline src/ride/station.c]: Hmm true should have thought it through a bit better than that.
